package initcmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/neural-chilli/fkn/internal/config"
)

func inferConfig(repoRoot string) string {
	project := filepath.Base(repoRoot)
	tasks := inferTasks(repoRoot)
	aliases := inferAliases(repoRoot, tasks)
	if len(tasks) == 0 {
		return starterConfig
	}

	var builder strings.Builder
	builder.WriteString(fmt.Sprintf("project: %s\n", project))
	builder.WriteString("description: Generated by fkn init --from-repo\n")
	if defaultTask := inferredDefaultTask(tasks); defaultTask != "" {
		builder.WriteString(fmt.Sprintf("default: %s\n", defaultTask))
	}
	builder.WriteString("\n")
	builder.WriteString("tasks:\n")
	for _, task := range tasks {
		builder.WriteString(fmt.Sprintf("  %s:\n", task.Name))
		builder.WriteString(fmt.Sprintf("    desc: %s\n", task.Desc))
		if task.Cmd != "" {
			builder.WriteString(fmt.Sprintf("    cmd: %s\n", task.Cmd))
		}
		if task.Agent != nil {
			builder.WriteString(fmt.Sprintf("    agent: %t\n", *task.Agent))
		}
		if task.Safety != "" {
			builder.WriteString(fmt.Sprintf("    safety: %s\n", task.Safety))
		}
		if len(task.Params) > 0 {
			builder.WriteString("    params:\n")
			for _, paramName := range sortedParamNames(task.Params) {
				param := task.Params[paramName]
				builder.WriteString(fmt.Sprintf("      %s:\n", paramName))
				if param.Desc != "" {
					builder.WriteString(fmt.Sprintf("        desc: %s\n", param.Desc))
				}
				builder.WriteString(fmt.Sprintf("        env: %s\n", param.Env))
				if param.Required {
					builder.WriteString("        required: true\n")
				}
				if param.Default != "" {
					builder.WriteString(fmt.Sprintf("        default: %s\n", param.Default))
				}
				if param.Position > 0 {
					builder.WriteString(fmt.Sprintf("        position: %d\n", param.Position))
				}
				if param.Variadic {
					builder.WriteString("        variadic: true\n")
				}
			}
		}
		if len(task.Steps) > 0 {
			builder.WriteString("    steps:\n")
			for _, step := range task.Steps {
				builder.WriteString(fmt.Sprintf("      - %s\n", step))
			}
		}
	}

	writeAliasConfig(&builder, aliases)
	writeGuardConfig(&builder, tasks)
	writeWatchConfig(&builder, repoRoot)
	return builder.String()
}

func inferTasks(repoRoot string) []inferredTask {
	taskByName := map[string]inferredTask{}
	order := []string{}

	addTask := func(name, desc, cmd string, agent *bool, safety string, params map[string]config.Param) {
		if _, exists := taskByName[name]; exists {
			return
		}
		taskByName[name] = inferredTask{Name: name, Desc: desc, Cmd: cmd, Agent: agent, Safety: safety, Params: params}
		order = append(order, name)
	}

	for _, target := range findMakeTargets(repoRoot) {
		if shouldSkipInferredTarget(target.Name) {
			continue
		}
		addTask(
			target.Name,
			inferredTargetDesc("repository", target.Name, "target"),
			fmt.Sprintf("make %s", target.Name),
			inferredTargetAgent(target.Name, len(target.Params) > 0),
			inferredTargetSafety(target.Name, len(target.Params) > 0),
			inferredParams(target.Params),
		)
	}

	for _, recipe := range findJustRecipes(repoRoot) {
		if shouldSkipInferredTarget(recipe.Name) {
			continue
		}
		addTask(
			recipe.Name,
			inferredTargetDesc("repository", recipe.Name, "recipe"),
			buildJustCommand(recipe),
			inferredTargetAgent(recipe.Name, len(recipe.Params) > 0),
			inferredTargetSafety(recipe.Name, len(recipe.Params) > 0),
			inferredJustParams(recipe.Params),
		)
	}

	scripts := findPackageScripts(repoRoot)
	scriptNames := make([]string, 0, len(scripts))
	for name := range scripts {
		scriptNames = append(scriptNames, name)
	}
	sort.Strings(scriptNames)
	for _, name := range scriptNames {
		script := scripts[name]
		if !shouldInferPackageScript(name, script) {
			continue
		}
		addTask(
			scriptTaskName(name),
			fmt.Sprintf("Run the package.json %s script", name),
			script.Cmd,
			inferredTargetAgent(name, len(script.Params) > 0),
			inferredTargetSafety(name, len(script.Params) > 0),
			script.Params,
		)
	}

	for _, task := range findRustTasks(repoRoot) {
		addTask(task.Name, task.Desc, task.Cmd, task.Agent, task.Safety, task.Params)
	}

	for _, task := range findPythonTasks(repoRoot) {
		addTask(task.Name, task.Desc, task.Cmd, task.Agent, task.Safety, task.Params)
	}

	for _, task := range findComposeTasks(repoRoot) {
		addTask(task.Name, task.Desc, task.Cmd, task.Agent, task.Safety, task.Params)
	}

	if hasFile(repoRoot, "go.mod") {
		addTask("test", "Run the Go test suite", "go test ./...", nil, "idempotent", nil)
		addTask("build", "Build the Go packages", "go build ./...", nil, "idempotent", nil)
	}

	if _, ok := taskByName["check"]; !ok {
		steps := []string{}
		for _, name := range []string{"lint", "test", "build"} {
			if _, exists := taskByName[name]; exists {
				steps = append(steps, name)
			}
		}
		if len(steps) >= 2 {
			taskByName["check"] = inferredTask{
				Name:  "check",
				Desc:  "Run the default local verification pipeline",
				Steps: steps,
			}
			order = append(order, "check")
		}
	}

	tasks := make([]inferredTask, 0, len(order))
	for _, name := range order {
		task, ok := taskByName[name]
		if !ok {
			continue
		}
		tasks = append(tasks, task)
	}

	return tasks
}

func writeAliasConfig(builder *strings.Builder, aliases map[string]string) {
	if len(aliases) == 0 {
		return
	}
	builder.WriteString("\naliases:\n")
	for _, name := range sortedAliasNames(aliases) {
		builder.WriteString(fmt.Sprintf("  %s: %s\n", name, aliases[name]))
	}
}

func writeGuardConfig(builder *strings.Builder, tasks []inferredTask) {
	guardSteps := inferredGuardSteps(tasks)
	if len(guardSteps) == 0 {
		return
	}
	builder.WriteString("\nguards:\n")
	builder.WriteString("  default:\n")
	builder.WriteString("    steps:\n")
	for _, step := range guardSteps {
		builder.WriteString(fmt.Sprintf("      - %s\n", step))
	}
}

func writeWatchConfig(builder *strings.Builder, repoRoot string) {
	if watchPaths := inferredWatchPaths(repoRoot); len(watchPaths) > 0 {
		builder.WriteString("\nwatch:\n")
		builder.WriteString("  debounce_ms: 500\n")
		builder.WriteString("  paths:\n")
		for _, path := range watchPaths {
			builder.WriteString(fmt.Sprintf("    - %s\n", path))
		}
	}
}

func inferredDefaultTask(tasks []inferredTask) string {
	for _, candidate := range []string{"check", "verify", "test", "build"} {
		for _, task := range tasks {
			if task.Name == candidate {
				return candidate
			}
		}
	}
	return ""
}

func inferredTargetDesc(subject, name, kind string) string {
	return fmt.Sprintf("Run the %s %s %s", subject, name, kind)
}

func inferAliases(repoRoot string, tasks []inferredTask) map[string]string {
	taskNames := map[string]bool{}
	for _, task := range tasks {
		taskNames[task.Name] = true
	}

	aliases := map[string]string{}
	for alias, target := range findJustAliases(repoRoot) {
		if strings.Contains(target, "::") {
			continue
		}
		if taskNames[target] {
			aliases[alias] = target
		}
	}
	return aliases
}

func inferredTargetAgent(name string, hasParams bool) *bool {
	if shouldHideFromAgents(name, hasParams) {
		value := false
		return &value
	}
	return nil
}

func inferredTargetSafety(name string, hasParams bool) string {
	lower := strings.ToLower(name)
	if lower == "clean" || tokenMatch(lower, "init") || strings.Contains(lower, "migrate") || strings.Contains(lower, "seed") || (hasParams && (strings.Contains(lower, "add") || strings.Contains(lower, "create") || strings.Contains(lower, "generate"))) {
		return "destructive"
	}
	for _, token := range []string{"deploy", "release", "publish", "sync"} {
		if tokenMatch(lower, token) {
			return "external"
		}
	}
	for _, token := range []string{"test", "check", "verify", "build", "lint", "fmt", "vet", "vulncheck"} {
		if lower == token || strings.HasPrefix(lower, token+"-") || strings.HasPrefix(lower, token+":") {
			return "idempotent"
		}
	}
	return ""
}

func tokenMatch(name, token string) bool {
	return name == token || strings.HasPrefix(name, token+"-") || strings.HasSuffix(name, "-"+token)
}

func shouldSkipInferredTarget(name string) bool {
	switch name {
	case "add-feature-git":
		return true
	default:
		return false
	}
}

func shouldHideFromAgents(name string, hasParams bool) bool {
	lower := strings.ToLower(name)
	if lower == "clean" {
		return true
	}
	if hasParams && (strings.Contains(lower, "add") || strings.Contains(lower, "create") || strings.Contains(lower, "init") || strings.Contains(lower, "generate") || strings.Contains(lower, "release") || strings.Contains(lower, "deploy") || strings.Contains(lower, "publish") || strings.Contains(lower, "migrate") || strings.Contains(lower, "seed") || strings.Contains(lower, "sync")) {
		return true
	}
	for _, token := range []string{"init", "sync", "release", "deploy", "publish", "migrate", "seed"} {
		if lower == token || strings.HasPrefix(lower, token+"-") || strings.HasSuffix(lower, "-"+token) {
			return true
		}
	}
	return false
}

func shouldInferPackageScript(name string, script packageScript) bool {
	switch name {
	case "check", "test", "build", "lint", "dev", "start", "release", "deploy", "publish", "generate":
		return true
	}
	if strings.HasPrefix(name, "test:") || strings.HasPrefix(name, "lint:") {
		return true
	}
	if len(script.Params) > 0 {
		return true
	}
	return false
}

func inferredGuardSteps(tasks []inferredTask) []string {
	names := map[string]bool{}
	for _, task := range tasks {
		names[task.Name] = true
	}
	steps := []string{}
	for _, name := range []string{"lint", "test", "build"} {
		if names[name] {
			steps = append(steps, name)
		}
	}
	if len(steps) == 0 && names["check"] {
		steps = []string{"check"}
	}
	return steps
}

func inferredWatchPaths(repoRoot string) []string {
	paths := []string{"README.md"}
	if hasFile(repoRoot, "go.mod") {
		paths = append(paths, "cmd/", "internal/", "go.mod")
	}
	if hasFile(repoRoot, "package.json") {
		paths = append(paths, "src/", "package.json")
	}
	if hasFile(repoRoot, "Makefile") {
		paths = append(paths, "Makefile")
	}
	if hasFile(repoRoot, "justfile") {
		paths = append(paths, "justfile")
	}
	if hasFile(repoRoot, "Justfile") {
		paths = append(paths, "Justfile")
	}
	paths = append(paths, rustWatchPaths(repoRoot)...)
	paths = append(paths, pythonWatchPaths(repoRoot)...)
	paths = append(paths, composeWatchPaths(repoRoot)...)

	seen := map[string]bool{}
	out := make([]string, 0, len(paths))
	for _, path := range paths {
		if seen[path] {
			continue
		}
		seen[path] = true
		out = append(out, path)
	}
	return out
}

func sortedTaskNames(tasks map[string]config.Task) []string {
	names := make([]string, 0, len(tasks))
	for name := range tasks {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedParamNames(params map[string]config.Param) []string {
	names := make([]string, 0, len(params))
	for name := range params {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedGuardNames(guards map[string]config.Guard) []string {
	names := make([]string, 0, len(guards))
	for name := range guards {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedGroupNames(groups map[string]config.Group) []string {
	names := make([]string, 0, len(groups))
	for name := range groups {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedPromptNames(prompts map[string]config.Prompt) []string {
	names := make([]string, 0, len(prompts))
	for name := range prompts {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedScopeNames(scopes map[string]config.Scope) []string {
	names := make([]string, 0, len(scopes))
	for name := range scopes {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedAliasNames(aliases map[string]string) []string {
	names := make([]string, 0, len(aliases))
	for name := range aliases {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func hasFile(repoRoot, name string) bool {
	entries, err := os.ReadDir(repoRoot)
	if err != nil {
		return false
	}
	for _, entry := range entries {
		if entry.Name() == name {
			return true
		}
	}
	return false
}

func hasDir(repoRoot, name string) bool {
	entries, err := os.ReadDir(repoRoot)
	if err != nil {
		return false
	}
	for _, entry := range entries {
		if entry.Name() == name && entry.IsDir() {
			return true
		}
	}
	return false
}
