package initcmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type Options struct {
	FromRepo bool
}

const starterConfig = `project: my-project
description: Describe your repository

tasks:
  test:
    desc: Run the test suite
    cmd: go test ./...

  build:
    desc: Build the application
    cmd: go build ./...

  check:
    desc: Run the default local verification pipeline
    steps:
      - test
      - build
`

type inferredTask struct {
	Name  string
	Desc  string
	Cmd   string
	Steps []string
}

func Run(repoRoot string, opts Options) (string, error) {
	var messages []string

	cfgPath := filepath.Join(repoRoot, "fkn.yaml")
	if _, err := os.Stat(cfgPath); err == nil {
		messages = append(messages, "fkn.yaml already exists; leaving it unchanged")
	} else if os.IsNotExist(err) {
		configBody := starterConfig
		if opts.FromRepo {
			configBody = inferConfig(repoRoot)
		}
		if err := os.WriteFile(cfgPath, []byte(configBody), 0o644); err != nil {
			return "", err
		}
		messages = append(messages, "created fkn.yaml")
		if opts.FromRepo {
			messages = append(messages, "scaffolded tasks from existing repo files")
		}
	} else {
		return "", err
	}

	updated, err := ensureGitignoreEntry(filepath.Join(repoRoot, ".gitignore"), ".fkn/")
	if err != nil {
		return "", err
	}
	if updated {
		messages = append(messages, "updated .gitignore with .fkn/")
	} else {
		messages = append(messages, ".gitignore already includes .fkn/")
	}

	return strings.Join(messages, "\n"), nil
}

func inferConfig(repoRoot string) string {
	project := filepath.Base(repoRoot)
	tasks := inferTasks(repoRoot)
	if len(tasks) == 0 {
		return starterConfig
	}

	var builder strings.Builder
	builder.WriteString(fmt.Sprintf("project: %s\n", project))
	builder.WriteString("description: Generated by fkn init --from-repo\n\n")
	builder.WriteString("tasks:\n")
	for _, task := range tasks {
		builder.WriteString(fmt.Sprintf("  %s:\n", task.Name))
		builder.WriteString(fmt.Sprintf("    desc: %s\n", task.Desc))
		if task.Cmd != "" {
			builder.WriteString(fmt.Sprintf("    cmd: %s\n", task.Cmd))
		}
		if len(task.Steps) > 0 {
			builder.WriteString("    steps:\n")
			for _, step := range task.Steps {
				builder.WriteString(fmt.Sprintf("      - %s\n", step))
			}
		}
	}

	guardSteps := inferredGuardSteps(tasks)
	if len(guardSteps) > 0 {
		builder.WriteString("\nguards:\n")
		builder.WriteString("  default:\n")
		builder.WriteString("    steps:\n")
		for _, step := range guardSteps {
			builder.WriteString(fmt.Sprintf("      - %s\n", step))
		}
	}

	if watchPaths := inferredWatchPaths(repoRoot); len(watchPaths) > 0 {
		builder.WriteString("\nwatch:\n")
		builder.WriteString("  debounce_ms: 500\n")
		builder.WriteString("  paths:\n")
		for _, path := range watchPaths {
			builder.WriteString(fmt.Sprintf("    - %s\n", path))
		}
	}

	return builder.String()
}

func inferTasks(repoRoot string) []inferredTask {
	taskByName := map[string]inferredTask{}
	order := []string{}

	addTask := func(name, desc, cmd string) {
		if _, exists := taskByName[name]; exists {
			return
		}
		taskByName[name] = inferredTask{Name: name, Desc: desc, Cmd: cmd}
		order = append(order, name)
	}

	for _, target := range findMakeTargets(repoRoot) {
		switch target {
		case "check":
			addTask("check", "Run the repository check target", "make check")
		case "test":
			addTask("test", "Run the repository test target", "make test")
		case "build":
			addTask("build", "Run the repository build target", "make build")
		case "lint":
			addTask("lint", "Run the repository lint target", "make lint")
		case "dev":
			addTask("dev", "Run the repository dev target", "make dev")
		}
	}

	for _, target := range findJustTargets(repoRoot) {
		switch target {
		case "check":
			addTask("check", "Run the repository check recipe", "just check")
		case "test":
			addTask("test", "Run the repository test recipe", "just test")
		case "build":
			addTask("build", "Run the repository build recipe", "just build")
		case "lint":
			addTask("lint", "Run the repository lint recipe", "just lint")
		case "dev":
			addTask("dev", "Run the repository dev recipe", "just dev")
		}
	}

	scripts := findPackageScripts(repoRoot)
	scriptNames := make([]string, 0, len(scripts))
	for name := range scripts {
		scriptNames = append(scriptNames, name)
	}
	sort.Strings(scriptNames)
	for _, name := range scriptNames {
		switch name {
		case "check":
			addTask("check", "Run the package.json check script", fmt.Sprintf("npm run %s", name))
		case "test":
			addTask("test", "Run the package.json test script", fmt.Sprintf("npm run %s", name))
		case "build":
			addTask("build", "Run the package.json build script", fmt.Sprintf("npm run %s", name))
		case "lint":
			addTask("lint", "Run the package.json lint script", fmt.Sprintf("npm run %s", name))
		case "dev":
			addTask("dev", "Run the package.json dev script", fmt.Sprintf("npm run %s", name))
		case "start":
			addTask("start", "Run the package.json start script", fmt.Sprintf("npm run %s", name))
		default:
			if strings.HasPrefix(name, "test:") {
				addTask(scriptTaskName(name), fmt.Sprintf("Run the package.json %s script", name), fmt.Sprintf("npm run %s", name))
			}
			if strings.HasPrefix(name, "lint:") {
				addTask(scriptTaskName(name), fmt.Sprintf("Run the package.json %s script", name), fmt.Sprintf("npm run %s", name))
			}
		}
	}

	if hasFile(repoRoot, "go.mod") {
		addTask("test", "Run the Go test suite", "go test ./...")
		addTask("build", "Build the Go packages", "go build ./...")
	}

	if _, ok := taskByName["check"]; !ok {
		steps := []string{}
		for _, name := range []string{"lint", "test", "build"} {
			if _, exists := taskByName[name]; exists {
				steps = append(steps, name)
			}
		}
		if len(steps) >= 2 {
			taskByName["check"] = inferredTask{
				Name:  "check",
				Desc:  "Run the default local verification pipeline",
				Steps: steps,
			}
			order = append(order, "check")
		}
	}

	tasks := make([]inferredTask, 0, len(order))
	for _, name := range order {
		task, ok := taskByName[name]
		if !ok {
			continue
		}
		tasks = append(tasks, task)
	}

	return tasks
}

func inferredGuardSteps(tasks []inferredTask) []string {
	names := map[string]bool{}
	for _, task := range tasks {
		names[task.Name] = true
	}
	steps := []string{}
	for _, name := range []string{"lint", "test", "build"} {
		if names[name] {
			steps = append(steps, name)
		}
	}
	if len(steps) == 0 && names["check"] {
		steps = []string{"check"}
	}
	return steps
}

func inferredWatchPaths(repoRoot string) []string {
	paths := []string{"README.md"}
	if hasFile(repoRoot, "go.mod") {
		paths = append(paths, "cmd/", "internal/", "go.mod")
	}
	if hasFile(repoRoot, "package.json") {
		paths = append(paths, "src/", "package.json")
	}
	if hasFile(repoRoot, "Makefile") {
		paths = append(paths, "Makefile")
	}

	seen := map[string]bool{}
	out := make([]string, 0, len(paths))
	for _, path := range paths {
		if seen[path] {
			continue
		}
		seen[path] = true
		out = append(out, path)
	}
	return out
}

func findMakeTargets(repoRoot string) []string {
	return findTargets(filepath.Join(repoRoot, "Makefile"))
}

func findJustTargets(repoRoot string) []string {
	return findTargets(filepath.Join(repoRoot, "justfile"))
}

func findTargets(path string) []string {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil
	}

	targetPattern := regexp.MustCompile(`(?m)^([A-Za-z0-9][A-Za-z0-9_-]*)\s*:`)
	matches := targetPattern.FindAllStringSubmatch(string(raw), -1)
	if len(matches) == 0 {
		return nil
	}

	seen := map[string]bool{}
	var targets []string
	for _, match := range matches {
		name := match[1]
		if seen[name] {
			continue
		}
		seen[name] = true
		targets = append(targets, name)
	}
	return targets
}

func findPackageScripts(repoRoot string) map[string]string {
	raw, err := os.ReadFile(filepath.Join(repoRoot, "package.json"))
	if err != nil {
		return nil
	}

	var pkg struct {
		Scripts map[string]string `json:"scripts"`
	}
	if err := json.Unmarshal(raw, &pkg); err != nil {
		return nil
	}
	return pkg.Scripts
}

func scriptTaskName(name string) string {
	replacer := strings.NewReplacer(":", "-", "/", "-")
	return replacer.Replace(name)
}

func hasFile(repoRoot, name string) bool {
	_, err := os.Stat(filepath.Join(repoRoot, name))
	return err == nil
}

func ensureGitignoreEntry(path, entry string) (bool, error) {
	raw, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}

	lines := []string{}
	if len(raw) > 0 {
		lines = strings.Split(strings.ReplaceAll(string(raw), "\r\n", "\n"), "\n")
		for _, line := range lines {
			if strings.TrimSpace(line) == entry {
				return false, nil
			}
		}
	}

	content := strings.TrimRight(string(raw), "\n")
	if content == "" {
		content = entry + "\n"
	} else {
		content = content + "\n" + entry + "\n"
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}
